name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
            
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true      

      - name: Build
        run: cargo build --verbose --release
        
      - name: Strip
        run: strip "target/release/proton-usage"

      - name: Get Version
        shell: bash
        run: |
          echo "PU_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
 
      - name: Package
        shell: bash
        run: ./package.sh "v${{ env.PU_VERSION }}"
      
      - name: Create Release Notes
        run: ci/latest-changes.sh > release-notes.txt
      
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: 'artifacts/*.tar.gz'
          body_path: release-notes.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
